/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package test;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 豆光耀
 */
public class EmployeeInformation extends javax.swing.JFrame {
    Connection con;
    private DefaultTableModel defaultTable1;
    private DefaultTableModel defaultTable2;
	private JTable table1=new JTable();
	private JTable table2=new JTable();
	String key;/**
     * Creates new form manager
     */
    public EmployeeInformation() {
        initComponents();
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jtablemianshi = new javax.swing.JTable();
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jLabel1.setText("当前为员工信息界面");
        jScrollPane1.setViewportView(table1);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        ))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
            
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)   
                .addGap(43, 43, 43)
                .addContainerGap(175, Short.MAX_VALUE))
        );
        
       defaultTable1=(DefaultTableModel)table1.getModel();
 	   defaultTable1.setRowCount(0);
 	   defaultTable1.setColumnIdentifiers(new Object[] {"员工号","姓名","性别","年龄","部门","职位","工资"});
 	   
 	   key =login.key;
 	String sql="select EMP.Eno ,Ename,Sex,Age,Dname,Pname,Salary\r\n" + 
 			"from EMP,WORK,DEP,POS\r\n" + 
 			"where\r\n" + 
 			"Emp.Eno ='"+key+"' and\r\n" + 
 			"Emp.Eno =WORK.Eno and\r\n" + 
 			"WORK.Pno =POS.Pno and\r\n" + 
 			"DEP.Dno =WORK.Dno";
 	try {
 		con=Main.getConnection();
 		Statement stat=con.createStatement();
 		ResultSet rs=stat.executeQuery(sql);
 		while(rs.next()) {
			defaultTable1.addRow(new Object[] {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)});
		}
		rs.close();
	
 	} catch (SQLException e) {
 		// TODO Auto-generated catch block
 		e.printStackTrace();
 	}
      pack();
    }// </editor-fold>   
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTable Jtablemianshi;
  
    private javax.swing.JLabel jLabel1;
 
    private javax.swing.JScrollPane jScrollPane1;
    
   
    // End of variables declaration                   
}
